# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('image', mezzanine.core.fields.FileField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('html', models.TextField()),
                ('link', models.CharField(blank=True, help_text=b'Optional, if provided clicking the image or blurb will go here.', max_length=2000)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='home.HomePage')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
    ]
