# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageblurb',
            name='html',
            field=models.TextField(blank=True, help_text=b'Extra html or alternative to Image field - eg, maps embed, FA Icon, etc'),
        ),
        migrations.AlterField(
            model_name='imageblurb',
            name='usage',
            field=models.CharField(choices=[(b'slider', b'slider'), (b'call-to-action', b'call-to-action'), (b'row-of-three', b'row-of-three'), (b'row-of-four', b'row-of-four'), (b'two-plus-one', b'two-lus-one'), (b'slider-overlay-left', b'slider-overlay-left'), (b'slider-overlay-right', b'slider-overlay-right'), (b'parallax-bottom', b'parallax-bottom')], max_length=20),
        ),
        migrations.AlterField(
            model_name='slide',
            name='html',
            field=models.TextField(blank=True, help_text=b'Alternative to Image field - eg, Video embed, etc'),
        ),
    ]
